### ISSUE TITLE
ES Module error on fresh clone

### ISSUE THREAD

**Issue by 1ak31sha** [whoisryosuke/next-mdx-deck#24]
just clone the repo to try this out. didnt make any code changes. used the node version from .nvmrc file (12.21.0)

run npm dev and get this error:

```bash
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/node_modules/@mdx-js/react/index.js
require() of ES modules is not supported.
require() of /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/node_modules/@mdx-js/react/index.js from /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/node_modules/@mdx-js/react/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.@mdx-js/react (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/pages/_app.js:469:18)
    at __webpack_require__ (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/MDXProvider.jsx:6:71)
    at Object../components/MDXProvider.jsx (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/pages/_app.js:74:1)
    at __webpack_require__ (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/webpack-runtime.js:33:42) {
  code: 'ERR_REQUIRE_ESM'
}
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/node_modules/@mdx-js/react/index.js
require() of ES modules is not supported.
require() of /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/node_modules/@mdx-js/react/index.js from /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/lakeishapogrzeba/workspace/git-next-mdx-deck/node_modules/@mdx-js/react/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.@mdx-js/react (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/pages/_app.js:469:18)
    at __webpack_require__ (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/MDXProvider.jsx:6:71)
    at Object../components/MDXProvider.jsx (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/pages/_app.js:74:1)
    at __webpack_require__ (/Users/lakeishapogrzeba/workspace/git-next-mdx-deck/.next/server/webpack-runtime.js:33:42) {
  code: 'ERR_REQUIRE_ESM'
}

```

**Comment by adamjarling** [comment]
@1ak31sha I ran into this same issue when installing packages via `npm install`, however running `yarn` instead to install dependencies seems to work ok.
